name: PR Build & Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    permissions:
      contents: read
    uses: IvanJosipovic/templates/.github/workflows/docker-build.yaml@main
 